### ISSUE TITLE
Error: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#165]
https://sentry.fuzzlesoft.ca/james-proxy/james/issues/43/

```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/home/mitch/dev/electron/out/D/resources/atom.asar/browser/objects-registry.js:48:28)
    at EventEmitter.<anonymous> (/home/mitch/dev/electron/out/D/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/home/mitch/dev/electron/out/D/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
  at None (/home/mitch/dev/james/build/index.html)
```

**Comment by mitchhentges** [comment]
Neat, this was made from Sentry.
Time to do that one more time, but with a gif
