### ISSUE TITLE
Doesnt work with Chrome HTTPS on OSX

### ISSUE THREAD

**Issue by avboy72** [james-proxy/james#363]
OSX 10.13.2

After following the https instructions....

When I try to use with Chrome, I cant access any https sites.  Just says "The site cant be reached".

If I open the developer console in James, I see the following error:

`index.js:46792 hoxy error:  Error: Invalid openssl exit code: 1
% openssl genrsa -rand /var/log/mail:/var/log/messages 2048
usage: genrsa [args] [numbits]
 -des            encrypt the generated key with DES in cbc mode
 -des3           encrypt the generated key with DES in ede cbc mode (168 bit key)
 -aes128, -aes192, -aes256
                 encrypt PEM output with cbc aes
 -camellia128, -camellia192, -camellia256
                 encrypt PEM output with cbc camellia
 -out file       output the key to 'file
 -passout arg    output file pass phrase source
 -f4             use F4 (0x10001) for the E value
 -3              use 3 for the E value
 -engine e       use engine e, possibly a hardware device.

    at done (file:///Applications/James.app/Contents/Resources/app.asar/index.js:46196:30)
    at ChildProcess.<anonymous> (file:///Applications/James.app/Contents/Resources/app.asar/index.js:46213:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)`

**Comment by avboy72** [comment]
James 1.5.0

**Comment by avboy72** [comment]
Found your 2.0.0 beta 3 tag and tried it.  Confirmed that Chrome works in that build. ( Note, that Safari doesnt proxy at all in that build, and Firefox doesnt proxy HTTPS )

**Comment by mitchhentges** [comment]
Huh, that's bizarre. Thanks for showing the console, that sheds some light - `hoxy` is choking on SSL? Hmm.
We're going to release `2.0.0` soon. If, like `beta.3`, that release _also_ doesn't have this issue, then let's close this ticket. Otherwise, we'll look into further investigation
